import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import SwirlQuick
import "../components"
import "../controls"

Item {
    id: page
    property var selected:null
    property bool followTail:true
    property var records:demoProvider.logs()
    readonly property var displayLogs:records.filter(function(r){
        return (r.message+" "+r.source+" "+r.level).toLowerCase().indexOf(search.text.toLowerCase())>=0 &&
               (level.currentText==="All levels"||r.level===level.currentText)
    }).map(function(r,i){return {id:"log-"+i,time:r.time,level:r.level,source:r.source,message:r.message}})
    ColumnLayout {
        anchors.fill:parent; anchors.margins:23; spacing:13
        RowLayout {
            Layout.fillWidth:true
            SwirlStatusBadge { label:"SIMULATED LOG STREAM"; tone:"accent" }
            Text { text:displayLogs.length+" entries · data never leaves this preview"; color:Theme.muted; font.pixelSize:12; Layout.fillWidth:true }
            SwirlButton { text:"Export"; iconName:"folder"; onClicked:AppState.notice("Export log records") }
            SwirlButton { text:"Clear"; danger:true; onClicked:{page.records=[];page.selected=null} }
        }
        RowLayout {
            Layout.fillWidth:true
            SwirlSearchField { id:search; Layout.fillWidth:true; placeholderText:"Search message, level or component" }
            SwirlComboBox { id:level; model:["All levels","INFO","DEBUG","WARN","ERROR"] }
            Text { text:"Follow tail"; color:Theme.muted; font.pixelSize:12 }
            SwirlToggle { checked:page.followTail; onToggled:page.followTail=checked }
        }
        RowLayout {
            Layout.fillWidth:true; Layout.fillHeight:true; spacing:14
            SwirlGlassPanel {
                Layout.fillWidth:true; Layout.fillHeight:true; clip:true
                SwirlDataTable {
                    anchors.fill:parent; anchors.margins:1
                    rows:page.displayLogs
                    selectedId:page.selected?page.selected.id:""
                    columns:[{key:"time",label:"TIME",w:108},{key:"level",label:"LEVEL",w:84},
                             {key:"source",label:"SOURCE",w:104},{key:"message",label:"MESSAGE",w:570}]
                    onRowSelected:function(r){page.selected=r}
                }
                SwirlEmptyState {
                    visible:page.displayLogs.length===0; anchors.centerIn:parent
                    headline:"No log entries"
                    detail:"Change filters or restore the synthetic dataset"
                }
            }
            SwirlGlassPanel {
                Layout.preferredWidth:289; Layout.fillHeight:true
                ColumnLayout {
                    anchors.fill:parent; anchors.margins:18; spacing:12
                    Text { text:"Event detail"; color:Theme.text; font.pixelSize:16; font.weight:Font.DemiBold }
                    SwirlStatusBadge { label:page.selected?page.selected.level:"NONE SELECTED"; tone:page.selected&&page.selected.level==="ERROR"?"warning":"neutral" }
                    Repeater {
                        model:[["TIME",page.selected?page.selected.time:"—"],["COMPONENT",page.selected?page.selected.source:"—"],
                               ["MESSAGE",page.selected?page.selected.message:"—"]]
                        ColumnLayout {
                            Layout.fillWidth:true; spacing:4
                            Text { text:modelData[0]; font.pixelSize:10; color:Theme.muted }
                            Text { text:modelData[1]; font.pixelSize:12; color:Theme.text; Layout.fillWidth:true; wrapMode:Text.WordWrap }
                        }
                    }
                    Rectangle { Layout.fillWidth:true; height:1; color:Theme.border }
                    Text { text:"DIAGNOSTIC EVENT"; color:Theme.muted; font.pixelSize:10 }
                    Text {
                        Layout.fillWidth:true
                        text:"Events shown in this preview are generated by DemoDataProvider. No system, Mihomo or Windows event log is read."
                        color:Theme.muted; font.pixelSize:12; wrapMode:Text.WordWrap
                    }
                    Item { Layout.fillHeight:true }
                    SwirlButton { text:"Restore demo logs"; onClicked:page.records=demoProvider.logs() }
                }
            }
        }
    }
}